#!/usr/bin/env bash
#SBATCH -p rome 
#SBATCH -w ziti-rome0
#SBATCH --exclusive
#SBATCH -o rome.txt


REPS=100

export OMP_PLACES=threads # threads for scan, otherwise numa_domains
export OMP_PROC_BIND=true


./../build/scan-benchmark_rome   --benchmark_time_unit=us --benchmark_out_format=csv --benchmark_out=scan_rome.csv \
                                         --benchmark_report_aggregates_only=true --benchmark_repetitions=$REPS \
                                         --benchmark_min_time=0.001 --benchmark_min_warmup_time=0.01

./../build/reduction-benchmark-gs_rome   --benchmark_time_unit=us --benchmark_out_format=csv --benchmark_out=reduction_rome.csv \
                                        --benchmark_report_aggregates_only=true --benchmark_repetitions=$REPS \
                                        --benchmark_min_time=0.001 --benchmark_min_warmup_time=0.01

./../build/transform-benchmark_rome   --benchmark_time_unit=us --benchmark_out_format=csv --benchmark_out=transform_rome.csv  \
                                      --benchmark_report_aggregates_only=true --benchmark_repetitions=$REPS \
                                      --benchmark_min_time=0.001 --benchmark_min_warmup_time=0.01


